//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskFromNikita
{
    using System;
    using System.Collections.Generic;
    
    public partial class payments
    {
        public int order_id { get; set; }
        public int money_id { get; set; }
        public int payment_sum { get; set; }
    
        public virtual money money { get; set; }
        public virtual orders orders { get; set; }
    }
}
